## Numpy come back

In [1]:
import numpy as np

## Masks revisions

With the randn method of numpy create a vector with 100 values

In [2]:
v = np.random.randn(100)

With a mask, select all values above 0.1 and store it in a vector v2

In [3]:
v2 = v[ v > 0.1 ]

with a mask select all values above 0.1 or below -0.1 and store it in a vector v3

In [4]:
v3 = v[(v > 0.1) | (v < -0.1) ]

## Vector shapes

Reshape the vector in a 10x10 matrix

In [5]:
v.reshape(10, 10)

array([[ 2.20072501, -1.12314568, -0.41153591,  1.01234109, -1.90419208,
         1.18577097,  0.32265522,  1.26386863,  0.32649176,  0.68120091],
       [ 1.04610329, -1.9288957 ,  0.17106798, -0.42707024,  1.18786521,
         1.97479073, -1.29871929, -0.97404293, -0.85041036, -2.28264382],
       [ 0.85640645, -1.12606863,  0.74076902,  0.06679498,  0.26763238,
         0.84897658, -0.15489586,  1.31133989, -0.41999437, -1.02738962],
       [-0.18655488,  1.3942952 ,  0.75598635, -1.04659688, -0.96992545,
         0.74493153,  0.03365677, -0.77751925, -0.27876147, -0.01023422],
       [ 1.26005506, -1.38285398, -0.64812483, -0.13781068,  2.61741759,
        -0.91187298,  0.76589964,  0.83532894, -0.4029281 , -2.77582728],
       [-1.60860534,  1.21545606, -0.4471645 ,  0.37363978, -0.56254628,
         0.08628989,  0.26666959, -1.33075261,  0.17553671,  0.98471644],
       [-0.07988344,  0.6158139 , -0.20596543,  1.917823  , -0.2526133 ,
         0.94176703,  0.06460622, -0.09075333

reshape the matrix into a 50x2 matrix

In [6]:
v.reshape(50,2)
# v.reshape(50,-1)

array([[ 2.20072501, -1.12314568],
       [-0.41153591,  1.01234109],
       [-1.90419208,  1.18577097],
       [ 0.32265522,  1.26386863],
       [ 0.32649176,  0.68120091],
       [ 1.04610329, -1.9288957 ],
       [ 0.17106798, -0.42707024],
       [ 1.18786521,  1.97479073],
       [-1.29871929, -0.97404293],
       [-0.85041036, -2.28264382],
       [ 0.85640645, -1.12606863],
       [ 0.74076902,  0.06679498],
       [ 0.26763238,  0.84897658],
       [-0.15489586,  1.31133989],
       [-0.41999437, -1.02738962],
       [-0.18655488,  1.3942952 ],
       [ 0.75598635, -1.04659688],
       [-0.96992545,  0.74493153],
       [ 0.03365677, -0.77751925],
       [-0.27876147, -0.01023422],
       [ 1.26005506, -1.38285398],
       [-0.64812483, -0.13781068],
       [ 2.61741759, -0.91187298],
       [ 0.76589964,  0.83532894],
       [-0.4029281 , -2.77582728],
       [-1.60860534,  1.21545606],
       [-0.4471645 ,  0.37363978],
       [-0.56254628,  0.08628989],
       [ 0.26666959,

Reshape the matrix into a 2x5x10 tensor (3D array)

In [7]:
v = v.reshape(2,5,10)

Compute the mean along the third axis of the 3D tensor

In [15]:
np.mean(v, axis=2)

array([[ 0.35541799, -0.33819551,  0.13635708, -0.03407223, -0.07807166],
       [-0.08467603,  0.23631526,  0.49757725, -0.05938357, -0.08764337]])

## Pandas come back

load the house dataset in a dataframe



In [9]:
import pandas as pd

In [10]:
df = pd.read_csv("../TP1/house.csv")
df

size  nb_rooms  garden orientation         price
0     95.056637         3       1         Est  9.514363e+05
1    139.862079         3       1         Sud  1.401691e+06
2    224.064203         3       0       Ouest  2.239801e+06
3    193.014152         1       1       Ouest  1.931833e+06
4    215.683859         1       1        Nord  2.158777e+06
5    203.231329         3       0        Nord  2.032797e+06
6    198.035370         2       1        Nord  1.980077e+06
7     77.249254         2       0         Est  7.732205e+05
8    145.876344         2       1       Ouest  1.459998e+06
9     50.094402         1       0       Ouest  5.019483e+05
10   113.365198         1       0       Ouest  1.132327e+06
11   124.712561         2       1         Sud  1.249095e+06
12    43.983091         1       0         Sud  4.399491e+05
13   130.994735         1       1         Sud  1.309238e+06
14   156.088254         3       1         Est  1.561483e+06
15   155.030166         1       1        Nord  1.545342e+06
16   137.095240         1       1        Nord  1.365680e+06
17   131.527548         2       0         Est  1.316757e+06
18   168.718099         2       1         Sud  1.686460e+06
19   146.886583         1       1        Nord  1.473543e+06
20   104.680927         2       1        Nord  1.046120e+06
21   202.927274         1       0         Sud  2.028517e+06
22   106.139943         1       0         Est  1.064126e+06
23   206.361554         3       0         Sud  2.063166e+06
24   151.401101         1       0        Nord  1.513740e+06
25    42.759520         2       1        Nord  4.290513e+05
26   169.316390         1       0         Sud  1.694488e+06
27   178.986853         3       1       Ouest  1.791620e+06
28   140.044549         1       1       Ouest  1.401725e+06
29   295.630840         1       0        Nord  2.953889e+06
..          ...       ...     ...         ...           ...
920  198.754261         3       0         Sud  1.987508e+06
921  173.240893         2       1         Sud  1.735132e+06
922  173.850916         1       1        Nord  1.744046e+06
923  182.886441         3       1        Nord  1.833059e+06
924  201.839394         3       0       Ouest  2.018918e+06
925  188.061832         3       1         Sud  1.881817e+06
926  112.269874         1       0         Sud  1.124379e+06
927  113.940219         2       0       Ouest  1.139728e+06
928   65.834424         1       1       Ouest  6.604754e+05
929  176.099622         3       1       Ouest  1.765859e+06
930  185.379033         2       1        Nord  1.853725e+06
931  117.677764         2       0         Sud  1.173512e+06
932   91.702945         2       1       Ouest  9.144660e+05
933  155.893128         2       0         Est  1.557050e+06
934  120.286479         2       1       Ouest  1.203815e+06
935  164.168196         3       1        Nord  1.643434e+06
936  134.293641         2       1       Ouest  1.340553e+06
937  161.603290         1       0         Est  1.611975e+06
938  141.812554         1       1         Sud  1.417248e+06
939  241.505469         2       0       Ouest  2.416476e+06
940   91.545135         1       1         Sud  9.213285e+05
941   21.011359         2       0        Nord  2.079491e+05
942  185.656034         1       1       Ouest  1.857637e+06
943  179.894926         1       0         Sud  1.797121e+06
944  190.143655         1       1        Nord  1.902467e+06
945   53.736489         2       1        Nord  5.346539e+05
946  106.746384         1       0         Est  1.068488e+06
947   70.338223         1       0         Est  7.038411e+05
948  122.106785         1       0         Est  1.226610e+06
949  175.439197         2       1        Nord  1.752890e+06

[950 rows x 5 columns]

With the groupby function, compute the average price of houses per number of bed rooms

In [18]:
df.groupby('nb_rooms').agg(np.mean)[['price']]

price
nb_rooms              
1         1.507739e+06
2         1.478317e+06
3         1.569152e+06

Do the same with garden

In [19]:
df.groupby('garden').agg(np.mean)[['price']]

price
garden              
0       1.512849e+06
1       1.522320e+06

Compute the median price by garden

In [20]:
df.groupby('garden').agg(np.median)[['price']]

price
garden              
0       1.540949e+06
1       1.519533e+06

Select the price column and put it in a variable s. Select the columns "bed rooms" and "price" in one way and put it a variable v. Print the type and shape of v and s

In [21]:
v = df[['nb_rooms', 'price']]
s = df['price']
v.shape, s.shape

((950, 2), (950,))